# Generated by Django 4.2.7 on 2023-11-21 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'authentication',
            '0003_remove_user_first_name_remove_user_last_name',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='date_joined',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message='Do not use whitespaces.',
                        regex='\\s',
                    )
                ],
                verbose_name='email address',
            ),
        ),
    ]
